services:
  - type: web
    name: aura-discord-bot
    env: python
    runtime: python-3.11.9
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true
    envVars:
      - key: DISCORD_TOKEN
        sync: false
